inputs:
  npm-token:
    required: true

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./.node-version
        registry-url: https://registry.npmjs.org/

    - run: corepack enable
      shell: bash

    - name: Can publish
      run: pnpm dlx can-npm-publish --verbose
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      shell: bash
