inputs:
  working-directory:
    required: true

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
        registry-url: https://registry.npmjs.org

    - run: corepack enable
      shell: bash

    - name: Install npm for publishing
      run: npm install -g npm@^11.5.1
      shell: bash

    - name: Run prepare
      run: pnpm prepare
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Build
      run: pnpm build
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Publish
      run: pnpm publish --no-git-checks --provenance --access public
      working-directory: ${{ inputs.working-directory }}
      shell: bash
