inputs:
  npm-token:
    required: true
  working-directory:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: ./.node-version
        registry-url: https://registry.npmjs.org/

    - run: corepack enable
      shell: bash

    - name: Run prepare
      run: pnpm prepare
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Build
      run: pnpm build
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Publish
      run: pnpm publish --provenance --no-git-checks
      working-directory: ${{ inputs.working-directory }}
      shell: bash
