// cspell:ignore defaultstatus
// eslint-config-airbnb-base@15.0.0 の compat.extends() 出力から機械生成。手編集しない。詳細は README.md を参照。
export const VARIABLES_RULES = {
  "init-declarations": "off",
  "no-catch-shadow": "off",
  "no-delete-var": "error",
  "no-label-var": "error",
  "no-restricted-globals": [
    "error",
    {
      message:
        "Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite",
      name: "isFinite",
    },
    {
      message:
        "Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan",
      name: "isNaN",
    },
    "addEventListener",
    "blur",
    "close",
    "closed",
    "confirm",
    "defaultStatus",
    "defaultstatus",
    "event",
    "external",
    "find",
    "focus",
    "frameElement",
    "frames",
    "history",
    "innerHeight",
    "innerWidth",
    "length",
    "location",
    "locationbar",
    "menubar",
    "moveBy",
    "moveTo",
    "name",
    "onblur",
    "onerror",
    "onfocus",
    "onload",
    "onresize",
    "onunload",
    "open",
    "opener",
    "opera",
    "outerHeight",
    "outerWidth",
    "pageXOffset",
    "pageYOffset",
    "parent",
    "print",
    "removeEventListener",
    "resizeBy",
    "resizeTo",
    "screen",
    "screenLeft",
    "screenTop",
    "screenX",
    "screenY",
    "scroll",
    "scrollbars",
    "scrollBy",
    "scrollTo",
    "scrollX",
    "scrollY",
    "self",
    "status",
    "statusbar",
    "stop",
    "toolbar",
    "top",
  ],
  "no-shadow": "error",
  "no-shadow-restricted-names": "error",
  "no-undef": "error",
  "no-undef-init": "error",
  "no-undefined": "off",
  "no-unused-vars": [
    "error",
    {
      args: "after-used",
      ignoreRestSiblings: true,
      vars: "all",
    },
  ],
  "no-use-before-define": [
    "error",
    {
      classes: true,
      functions: true,
      variables: true,
    },
  ],
}
