name: local-eslint-config-ts@CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - local/**
    paths:
      - '.node-version'
      - 'config/**'
      - 'dry-run/dr-eslint-config-sc-ts/**'
      - 'modules/shared-for-eslint-config/**'
      - 'packages/eslint-config-ts/**'
      - 'prettier.config.js'
      - 'pnpm-lock.yaml'

env:
  WORKING_DIRECTORY: ./packages/eslint-config-ts


jobs:
  local-dry-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: Run prepare
        run: pnpm prepare:copy-shared

      - name: Run lint
        run: pnpm lint


      - name: Run spell-check
        run: pnpm spell-check

      - name: Run type-check
        run: pnpm type-check


      - name: Run dry run
        run: pnpm dry-run
