name: root@CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop
      - feature/**
      - main
    paths:
      - '.node-version'
      - 'config/**'
      - 'cspell.config.js'
      - 'eslint.config.mjs'
      - 'packages/eslint-plugin-js/**'
      - 'prettier.config.js'
      - 'scripts/**'
      - 'pnpm-lock.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: Run post-install
        run: pnpm postinstall:copy-shared

      - name: Run lint
        run: pnpm lint

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: Run post-install
        run: pnpm postinstall:copy-shared

      - name: Run spell-check
        run: pnpm spell-check
